# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'haejwo-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for haejwo-ios
  pod 'Firebase', '~> 5.0.1' 
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end
